[project]
name = "04-yfinance"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.1",
    "pip>=25.0.1",
    "yfinance>=0.2.56",
]
